## 数据操作
### 数据性质和函数
首先导入torch  ~~虽然被称为PyTorch~~

In [1]:
import torch

张量表示一个数值组成的数组，这个数组可能有多个维度

In [105]:
x = torch.arange(12)
# x = x.reshape(3,2,2)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过张量的shape属性来访问张量的形状 和张量中元素的总数

In [106]:
x.shape

torch.Size([12])

In [107]:
x.numel()

12

改变一个张量的形状而不改变元素数量和元素值，调用reshape函数

In [104]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

reshape不改变地址 改一个地方等于全改

In [91]:
a = torch.arange(12)
b = a.reshape(3,4)
b[:] = 2
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

使用全0、1或者从特定分布中随机采样

In [6]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

通过提供包含数值的Python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值
-> tensor是张量的意思

In [7]:
torch.tensor([[2,1,4,3],[1,2,3,4]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4]])

### 数据的运算
常见的标准算术运算符（+、-、*、/和**）可以被升级为按元素运算

In [8]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y, x -y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素方式应用更多的计算  指数

In [9]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

把张量连结在一起  cat
* dim = 0 按行
* dim = 1 按列

In [10]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0), torch.cat((X,Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算符构建二元张量

In [11]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行求和会产生一个只有一个元素的张量。

In [12]:
X.sum()

tensor(66.)

即使形状不同，我们仍然可以通过调用广播机制(broadcasting mechanism)来执行按元素操作

In [13]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [14]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 数据的选择和修改
可以用[-1]选择最后一个元素，可以用[1：3]选择第二个和第三个元素

In [15]:
X, X[-1], X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

除读取外，我们还可以通过指定索引来将元素写入矩阵。

In [16]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。

In [17]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 数据的内存分配
运行一些操作可能会导致为新结果分配内存
* 特别大的矩阵不要一赋值

In [18]:
before = id(Y)
Y = Y + X
id(Y) == before

False

执行原地操作
* 进行数据的改写会在原内存

In [19]:
Z = torch.zeros_like(Y)
print('id(z):', id(Z))
Z[:] = X + Y
print('id(z):', id(Z))

id(z): 1774107988352
id(z): 1774107988352


如果在后续计算中没有重复使用X,我们也可以使用X[:]=X + Y或X += Y来减少操作的内存开销。

In [20]:
before = id(X)
X += Y
id(X) == before

True

### 与py数据的转换
转换为NumPy张量

In [21]:
A = x.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为Python标量

In [22]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 数据预处理
创建一个人工数据集，并存储在csv（逗号分隔值）文件

In [28]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True) # 相对路径创建文件 上一级目录
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

从创建的csv文件中加载原始数据集

In [32]:
# 如果没有安装pandas，只需取消对以下行的注释来安装pandas
# !pip install pandas
import pandas as pd

data = pd.read_csv(data_file)
print(data)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

为了处理缺失的数据，典型的方法包括插值和删除，这里，我们将考虑插值

In [86]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs[1:].mean())  # 要去除列名
# mean()里加上参数numeric_only=true
# inputs['NumRooms'] = inputs['NumRooms'].fillna(inputs['NumRooms'].mean())

print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


对于inputs中的类别值或离散值，我们将“NaN”视为一个类别。
* 将分类变量转换为虚拟变量（即哑变量）
* 设置 dummy_na=True，你可以将缺失值（NaN）也转化为一个新的虚拟变量。
* .astype(float) 将true 变成 1.0

In [89]:
# inputs.iat[1, 1] = "Save"  # 这里的 1, 1 是行和列的整数索引
inputs = pd.get_dummies(inputs, dummy_na=True).astype(float)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0         1.0        0.0
1       2.0         0.0        1.0
2       4.0         0.0        1.0
3       3.0         0.0        1.0


现在inputs和outputs中的所有条目都是数值类型，它们可以转换为张量格式。

In [90]:
import torch

x, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
x, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))