## 线性代数
* 标量
* 向量
  * 点乘  正交=0
* 矩阵
  * 乘法（最基础） -> 扭曲空间
  * 范数
    * 矩阵范数
    * Frobenius范数
  * 正定矩阵  乘以任何 大于等于0（不用很多）
  * 正交矩阵
  * 置换矩阵
  * 特征向量和特征值  （对称矩阵总数能找到特征向量）
  * https://www.bilibili.com/video/BV1ys411472E/?p=1&vd_source=cf898465da2e45ac7687b693fdb55695

### 基础操作

In [5]:
import torch

x = torch.arange(12).reshape(3,4)
x, x[2]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([ 8,  9, 10, 11]))

访问张量的长度

In [6]:
len(x), x.shape

(3, torch.Size([3, 4]))

矩阵的转置
* 对称矩阵的转置等于原矩阵

In [15]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B, B == B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构
* 层
* 行
* 列

In [17]:
x = torch.arange(24).reshape(2, 3, 4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是箱筒形状的张量

In [26]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
C = A
print(id(A), id(B),id(C))
A, A + B, id(A) == id(C)

2508624243104 2508624242624 2508624243104


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 True)

### 计算
两个矩阵的按元素乘法称为哈达玛积(Hadamard product)(数学符号⊙)

In [27]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [ ]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

计算其元素的和

In [30]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

表示任意形状张量的元素和

In [50]:
A = torch.arange(20*2).reshape(2, 5, 4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780))

指定求和汇总张量的轴

In [51]:
A_sum_axis0 = A.sum(axis=0) # 按照维度求和 0为在第一个维度 1为在第二个维度
A, A_sum_axis0, A_sum_axis0.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [52]:
A.sum(axis=[0, 1]),A.sum(axis=[0, 1]).shape

(tensor([180, 190, 200, 210]), torch.Size([4]))

一个与求和相关的量是 平均值(mean或average)
* mean只能浮点数

In [56]:
A = A.float()
A.mean(), A.sum() / A.numel()

(tensor(19.5000), tensor(19.5000))

按照维度求mean

In [59]:
A, A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

计算总和或均值时保持轴数不变

In [60]:
sum_A = A.sum(axis=0, keepdims=True) # 使得求和后维度不变 能使用广播机制 （不去掉维度 -> 变成1）
sum_A2 = A.sum(axis=0)
sum_A, sum_A2

(tensor([[[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]),
 tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]))

通过广播将A除以sum_A

In [61]:
A / sum_A, A / sum_A2

(tensor([[[0.0000, 0.0455, 0.0833, 0.1154],
          [0.1429, 0.1667, 0.1875, 0.2059],
          [0.2222, 0.2368, 0.2500, 0.2619],
          [0.2727, 0.2826, 0.2917, 0.3000],
          [0.3077, 0.3148, 0.3214, 0.3276]],
 
         [[1.0000, 0.9545, 0.9167, 0.8846],
          [0.8571, 0.8333, 0.8125, 0.7941],
          [0.7778, 0.7632, 0.7500, 0.7381],
          [0.7273, 0.7174, 0.7083, 0.7000],
          [0.6923, 0.6852, 0.6786, 0.6724]]]),
 tensor([[[0.0000, 0.0455, 0.0833, 0.1154],
          [0.1429, 0.1667, 0.1875, 0.2059],
          [0.2222, 0.2368, 0.2500, 0.2619],
          [0.2727, 0.2826, 0.2917, 0.3000],
          [0.3077, 0.3148, 0.3214, 0.3276]],
 
         [[1.0000, 0.9545, 0.9167, 0.8846],
          [0.8571, 0.8333, 0.8125, 0.7941],
          [0.7778, 0.7632, 0.7500, 0.7381],
          [0.7273, 0.7174, 0.7083, 0.7000],
          [0.6923, 0.6852, 0.6786, 0.6724]]]))

某个轴计算A元素的累计总和
* 前缀和

In [67]:
A = torch.arange(20).reshape(5,4)
A, A.cumsum(axis=0)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  6,  8, 10],
         [12, 15, 18, 21],
         [24, 28, 32, 36],
         [40, 45, 50, 55]]))

点积是相同位置的按元素乘积的和
* 是标量

In [68]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积

In [69]:
torch.sum(x * y)

tensor(6.)

矩阵向量积Ax是一个长度为m的列向量，其i元素是点积a^T_i_ x

In [80]:
# A.type(), x.type()
A = A.float()
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

我们可以将矩阵-矩阵乘法AB看作是简单地执行m次矩阵-向量积，并将结果拼接在一起，形成一个nXm矩阵

In [82]:
B = torch.ones(4, 3)
A, B, torch.mm(A, B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

### 范数
L2范数是向量元素平方和的平方根：

In [83]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

L1范数，它表示为向量元素的绝对值之和：

In [84]:
torch.abs(u).sum()

tensor(7.)

矩阵的弗罗贝尼乌斯范数(Frobenius norm)是矩阵元素的平方和的平方根：
* 相当于拉长矩阵变成向量

In [86]:
torch.ones((4, 9)), torch.norm(torch.ones((4, 9)))

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor(6.))